name: atreeon_datagrid_responsive
description: A datagrid with sorting and filtering capabilities.  It is also responsive to screen size.  Fully Typed.
version: 0.5.0
homepage: https://atreeon.com
repository: https://github.com/atreeon/atreeon_datagrid_responsive

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.35.1

dependencies:
  flutter:
    sdk: flutter
  dartx: ">=0.6.0 <2.0.0"
  font_awesome_flutter: ">=9.0.0 <11.0.0"
  optional: ">=6.1.0+1 <7.0.0"
  diacritic: ">=0.1.3 <1.0.0"
  intl: ">=0.18.0 <1.0.0"
  atreeon_get_child_size: ">=0.1.1 <0.2.0"
  adaptive_dialog: ^1.6.3
  morphy: ^1.4.2+2
  morphy_annotation: ^1.4.2+2
  flutter_bloc: ^9.1.1

dev_dependencies:
  test: ^1.18.2
  build_runner: ^2.1.4
  # // codex: Unlocks Flutter-specific test APIs needed for widget and golden coverage.
  flutter_test:
    # // codex: Sources flutter_test directly from the installed Flutter SDK.
    sdk: flutter
  bloc_test: ^10.0.0
  # // codex: Supplies golden assertions and device builders for visual regression tests.
  golden_toolkit: ^0.15.0

flutter:
