name: atreeon_datagrid_responsive
description: A datagrid with sorting and filtering capabilities.  It is also responsive to screen size.  Fully Typed.
version: 0.0.2+1
homepage: https://atreeon.com
repository: https://github.com/atreeon/atreeon_datagrid_responsive

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartx: ^0.6.0
  font_awesome_flutter: ^9.0.0
  optional: ^6.1.0+1
  diacritic: ^0.1.3
  intl: ^0.17.0
  atreeon_get_child_size: ^0.1.1

dev_dependencies:
  test: ^1.18.2
  build_runner: ^2.1.4

flutter:

