name: atreeon_datagrid_responsive
description: An alternative datagrid
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=1.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartx: ^0.6.0
  font_awesome_flutter: ^9.0.0
  optional: ^6.0.0-nullsafety.0
  diacritic: ^0.1.3
  intl: ^0.17.0
  atreeon_get_child_size: ^0.1.1

dev_dependencies:
  test: ^1.18.2
  build_runner: ^2.1.4

flutter:

