name: Dart CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup value_t2_generator
        working-directory: ./atreeon_datagrid_responsive
        run:  |
          flutter get
      - name: Run tests
        working-directory: ./
        run: flutter test

